### ISSUE TITLE
Fails to import multiple files of same name

### ISSUE THREAD

**Issue by mogelbrod** [LearnBoost/stylus#1403]
Stylus (v0.42.2) has problems `@import`ing multiple files with the same name (in different directories). This possibly has to do with directory index-based imports.

Example
---------

**Directory structure:**
```
* test/
  - file.styl
  - index.styl
* file.styl
* index.styl
```

*index.styl*
```stylus
.index
  color #001

@import "./test/index"
@import "./file"
```
*file.styl*
```
.file
  color #002
```
*test/index.styl*
```
.test.index
  color #003

@import "./file"
```
*test/file.styl*
```
.test.file
  color #004
```

**Result:**

*test/file.styl* is imported twice, once in place of *file.styl*.

```
$ stylus --version; stylus -c css/index.styl && cat css/index.css
0.42.2
  compiled css/index.css
.index{color:#001}
.test.index{color:#003}
.test.file{color:#004}
.test.file{color:#004}
```

**Expected:**
```
.index{color:#001}
.test.index{color:#003}
.test.file{color:#004}
.file{color:#002}
```

Observations
---------------

Stylus works as expected when the line `@import "./test/index"` is changed to `@import "./test"`, or when it's moved to the line below `@import "./file"`.

**Comment by Panya** [comment]
Fixed in the `dev` branch. The fix will be in the next release.

**Comment by tiagofelipe** [comment]
This problem persist. My version is 0.54.5

in app.styl file:

@import './mixins/buttons.styl'
@import './buttons.styl'

stylus --deps app.styl results:
mixins/buttons.styl
